### ISSUE TITLE
Invalid path double slash for vscode files 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/storage-gcs#88]
link generated for internal storage on vscode : `gs://internal_storage_-prd//demo/com/kestra/lde/_files/.vscode/settings.json`

see the `//` that lead to: 
![image](https://github.com/kestra-io/storage-gcs/assets/2064609/e3de4f2d-437a-4782-be07-77edc882b4d4)

**Comment by brian-mulier-p** [comment]
I'll close this as I think there is no issue in the end, the first slash is something that is present from before namespace files and execution data are already stored under such path. I believe you misthought that it was causing an issue but the real issue was [this one](https://github.com/kestra-io/kestra-ee/issues/670)
